# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


# класс образованный от .ui файла для создания или редактирования элемента
class ItemWidgetFromUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 115)
        Dialog.setWindowTitle("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 3)

        self.retranslate_ui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "Название"))
        self.label_2.setText(_translate("Dialog", "Путь"))
        self.pushButton_2.setText(_translate("Dialog", "Сохранить"))


class AddItem(QtWidgets.QDialog, ItemWidgetFromUi):  # наследуемый класс для создания элемента
    def __init__(self, parent_=None):
        super(AddItem, self).__init__()
        self.setupUi(self)
        self.parent_ = parent_
        self.setWindowTitle("Добавить элемент")
        self.pushButton.clicked.connect(self.path_name)  # обращение к методу для открытия FileDialog
        self.pushButton_2.clicked.connect(self.add_item)  # кнопка сохранить

    def add_item(self):
        if self.lineEdit.text() and self.lineEdit_2.text():  # если поля не пустые
            self.parent_.cur.execute(f'''INSERT INTO {self.parent_.comboBox.currentText()}("Название", "Путь")
             VALUES("{self.lineEdit.text()}", "{self.lineEdit_2.text()}")''')  # добавления элемента
            self.parent_.con.commit()  # сохранение данных
            self.hide()
            self.parent_.update_table()  # обновление TableWidget
        else:
            self.label_3.setText("Неверный запрос")

    def path_name(self):
        self.fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Выбрать файл', '')[0]
        self.lineEdit_2.setText(self.fname)


class ChangeItem(QtWidgets.QDialog, ItemWidgetFromUi):  # наследуемый класс для редактирования элемента
    def __init__(self, parent_=None):
        super(ChangeItem, self).__init__()
        self.setupUi(self)
        self.parent_ = parent_
        self.setWindowTitle("Редактировать элемент")
        self.pushButton.clicked.connect(self.path_name)
        self.pushButton_2.clicked.connect(self.change_item)
        self.lineEdit.setText(self.parent_.select_data[1])  # заполение в поле старого названия элемента
        self.lineEdit_2.setText(self.parent_.select_data[2])  # заполение в поле старого пути элемента

    def change_item(self):
        if self.lineEdit.text() and self.lineEdit_2.text():  # если поля не пустые
            self.parent_.cur.execute(f'''UPDATE {self.parent_.comboBox.currentText()}
            SET "Название" = '{self.lineEdit.text()}', "Путь" = "{self.lineEdit_2.text()}"
            WHERE "ID" = {self.parent_.select_data[0]}''')  # обновления данных
            self.parent_.con.commit()  # сохранение даных
            self.hide()
            self.parent_.update_table()  # обновление TableWidget
        else:
            self.label_3.setText("Неверный запрос")

    def path_name(self):
        self.fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Выбрать файл', '')[0]
        self.lineEdit_2.setText(self.fname)
