# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets


class NewTableFromUi(object):  # класс образованный от .ui файла для создания новой таблицы
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(235, 104)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)

        self.retranslate_ui(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создать новый раздел"))
        self.label.setText(_translate("Dialog", " Название"))
        self.pushButton.setText(_translate("Dialog", "Добавить"))


class NewTable(QtWidgets.QDialog, NewTableFromUi):  # наследуемый класс для создания новой таблицы
    def __init__(self, parent_=None):
        super(NewTable, self).__init__()
        self.setupUi(self)
        self.parent_ = parent_
        self.pushButton.clicked.connect(self.create_table)  # обращению к методу для создания таблицы

    def create_table(self):
        self.label_2.setText("")
        self.text = self.lineEdit.text()
        if self.text == "":  # если название пустое
            self.label_2.setText("Пустое название")
        else:
            self.con = sqlite3.connect("LaunchApp.sqlite")  # подключение к базе данных
            self.cur = self.con.cursor()
            self.cur.execute(f'''
CREATE TABLE "{self.text}" (
    "ID"	INTEGER UNIQUE,
    "Название"	TEXT,
    "Путь"	TEXT NOT NULL,
    PRIMARY KEY("ID" AUTOINCREMENT)
)''')  # создания раздела(таблицы)
            self.con.commit()  # сохранение таблицы
            self.con.close()  # закрытие таблицы
            self.parent_.comboBox.addItem(self.text)  # добавление названия нового раздела в ComboBox
            self.parent_.comboBox.setCurrentIndex(self.parent_.comboBox.findText(self.text))  # выбор новой таблицы
            self.parent_.update_table()  # обновление таблицы
            self.parent_.last_open_table(self.text)  # сохранение новой таблицы как последняя откратая таблицы
            self.hide()
